### ISSUE TITLE
change background-menu music

### ISSUE THREAD

**Issue by GoukiKain** [TeamPandory/pandory500#14]
Is there a way to change the background-menu music that is playing while choosing games and options?
I tried changing the mp3s in the "bgm" folder with custom ones but they aren't played at all.
The songs included are cool but I'd like more some UT and Battle Garegga (I'm weird like that).
Greetings and thanks to the developers of this amazing mod!

**Comment by dajoho** [comment]
They should work. Try making sure they don't have spaces in their names.
