### ISSUE TITLE
mount A500 filesystem with write permissions

### ISSUE THREAD

**Issue by grzegorzkyc** [TeamPandory/pandory500#15]
Hi, is there a way to have write access to the A500 mini filesystem from the built-in Pandory linux terminal?

I want to permanently edit the gamecontrollerdb.txt file to add support for my gamepad. I am not able to make any changes to this file because of the "read-only filesystem" error.

Thank you for the great mod!

**Comment by dajoho** [comment]
`mount -o remount,rw /`      should do the trick
