### ISSUE TITLE
Pandory a500 launching issue

### ISSUE THREAD

**Issue by Seany1889** [TeamPandory/pandory500#17]
Hi there
I don’t know if you can help or advise me. I’ve installed the pandory on a 128gb usb and loaded it fine on the a500 mini but after making some changes i.e. adding roms, changing configs etc when I try to launch pandory again I get the attached screen. I’ve looked online and can’t find a solution. Any ideas what I might be doing wrong or a solution to allow pandory to load ok?

Many thanks

Sean
![IMG_0232](https://user-images.githubusercontent.com/123760364/215144725-2ff45d18-08f8-4594-aa66-6cb98cb57a82.gif)

**Comment by dajoho** [comment]
Hi Sean,

Sure. Copy the pandory_ol.uae file from your original download in to the Pandory folder on the USB. The system overwrites it if you open the settings window.
