### ISSUE TITLE
Sega Saturn core

### ISSUE THREAD

**Issue by actraiser30** [TeamPandory/pandory500#18]
Hello

is there going to be support for a Retroarch core for the Sega Saturn ??

the Included Sega Saturn core does not work,

i have put the bios files to the correct folder

Thanks

**Comment by dajoho** [comment]
I'm afraid the Saturn is very hard to emulate and you never really get satisfactory performance unless you play with settings or disconnect video/audio sync and then you get farting audio. There is a saturn core in the new v3 version on the releases page if you wish to try it out. We're not attempting to support it although YMMV.
