### ISSUE TITLE
2 Player Mode / Glitch

### ISSUE THREAD

**Issue by Nostalgia2046** [TeamPandory/pandory500#19]
I have an issue since I installed Pandory v2 on the A500 mini. 

2 Players games are impossible to play solo,  reason is it will always start player 2 when I press the right button. :/ And this happens in every 2 players game. 

Thanks for the great work.

**Comment by dbriard** [comment]
I have the same issue, and was not able to configure pad  for 1 player only :(

**Comment by Nostalgia2046** [comment]
Yup and it seems this will never change  from what I understood. Too bad I guess :/

**Comment by dajoho** [comment]
Hi there. We have released a new version v3 today with many controller bugfixes. You may have better luck now. https://github.com/TeamPandory/pandory500/releases/tag/v3
