### ISSUE TITLE
Shutdown on 1.2.1?

### ISSUE THREAD

**Issue by dualmeower** [TeamPandory/pandory500#20]
Hi, when I start Pandory, THEA500 Mini that I have abruptly shuts down with a black screen and no way to toggle power, the only way to turn it off is by unplugging the cable. May you guys make a patch to work on firmware version 1.2.1?

**Comment by dajoho** [comment]
Hi there. Try out the new Pandory v3, released today. https://github.com/TeamPandory/pandory500/releases/tag/v3
