### ISSUE TITLE
no more works after firmware update (1 may 2022)

### ISSUE THREAD

**Issue by psypoker** [TeamPandory/pandory500#3]
the pandora mini 500 no more works after firmware update of the 500 mini

**Comment by sebbl2** [comment]
Same here for FW Update on May 13.. it only will load the amiga dos

**Comment by retrofun** [comment]
NOTE: THEA500 Mini Firmware 1.1.0 / 11 May 2022 has been removed due to issues.

https://retrogames.biz/support/thea500-mini/upgrade/
"The current firmware update has been temporarily removed while we address some issue and improve it further.

A new release will be published soon - Please check back for more infomation."

**Comment by retrofun** [comment]
Firmware 1.1.1 / 13 May 2022 was released!

**Comment by TeamPandory** [comment]
1.1.1, or any firmware update by them will not un-do the firmware vulnerability.
It's likely they rushed out the update due to the release of our tool.

**Comment by Wizart009** [comment]
no working by me to get the dos screen with error 
installed latest version of firmware 1.1.1

**Comment by Medizinmann-MD** [comment]
> Firmware 1.1.1 / 13 May 2022 was released!

Are there any plans in reenabling the pandory mod - that was killed with the firmware updates?

The ability to use pandory mod on the Amiga A500mini is/was the main selling point for me.

**Comment by Wizart009** [comment]
is there already solution for this ?

**Comment by Medizinmann-MD** [comment]
> is there already solution for this ?

AFAIK no - and I don't think that something is coming anytime soon.

**Comment by Luikuri** [comment]
Aw crud! Just updated to 1.1.1 before I noticed this project. And apparently no way to downgrade the fw either?

**Comment by dajoho** [comment]
@Luikuri Check the latest update in the releases section. Works on 1.1.1
