### ISSUE TITLE
Unable to quit back to the original menu or turn off properly

### ISSUE THREAD

**Issue by sssembler** [TeamPandory/pandory500#4]
So I can see no way to close retro arch once open and also if I try and shut down the a500 mini by holding the power it will lock up.  Any way to actually do this?

Thanks for this however, love playing the PC point and clicks on the A500 mini (I used to play the Amiga versions back in the day but the speech and wider range of games is a must and with the tank mouse it is very cool)

**Comment by dajoho** [comment]
Go to the "Applications" menu and select "A500 menu". That should let you switch back to the default menu.
