### ISSUE TITLE
Usb snd modules

### ISSUE THREAD

**Issue by claudiologiudice** [TeamPandory/pandory500#5]
Is possible to add in the new release the support for usb audio devices?
Eg.
Bus 001 Device 004: ID 8086:0808 Intel Corp. USB PnP Sound Device
This is on ubuntu:
[ 10.426115] usb 1-3: New USB device found, idVendor=8086, idProduct=0808, bcdDevice= 1.00
[ 10.426121] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 10.426122] usb 1-3: Product: USB PnP Sound Device
[ 10.426123] usb 1-3: Manufacturer: C-Media Electronics Inc.
[ 10.453889] hid: raw HID events driver (C) Jiri Kosina
[ 10.459227] usbcore: registered new interface driver usbhid
[ 10.459232] usbhid: USB HID core driver
[ 10.468015] IPv6: ADDRCONF(NETDEV_CHANGE): wlo1: link becomes ready
[ 10.469491] usbcore: registered new interface driver snd-usb-audio
[ 10.503533] input: C-Media Electronics Inc. USB PnP Sound Device as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.3/0003:8086:0808.0001/input/input16

Thanx for your work!!!

**Comment by dajoho** [comment]
I am afraid this is on hold for the moment as it interferes with the network drivers we load. Sorry!
